# Generated by Django 3.1.7 on 2022-03-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='choose a language for the book e.g. Arabic, English, Faresi,etc.', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='lang',
            field=models.ManyToManyField(help_text='Choose a languages you write with.', to='catalog.Languages'),
        ),
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.languages'),
        ),
    ]
