# Generated by Django 3.1.7 on 2022-03-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220308_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='gener',
            name='name',
            field=models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=100),
        ),
        migrations.AlterField(
            model_name='languages',
            name='name',
            field=models.CharField(help_text='choose a language for the book e.g. Arabic, English, Faresi,etc.', max_length=100),
        ),
    ]
