# Generated by Django 3.1.7 on 2022-04-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20220406_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_buy', 'can buy'),)},
        ),
    ]
