# Generated by Django 3.1.7 on 2022-04-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20220406_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_view_book_instance', 'Can view book instance'))},
        ),
    ]
