# Generated by Django 3.1.7 on 2022-05-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20220409_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('view_book_c', 'View book instances'),)},
        ),
    ]
