# Generated by Django 3.1.7 on 2022-05-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220515_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('view_book_c', 'View book instances'), ('can_create_book', 'Can create book'))},
        ),
    ]
