# Generated by Django 3.1.7 on 2022-05-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20220516_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summery',
            field=models.TextField(help_text='write a brief summary of the book', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Book title', max_length=60),
        ),
    ]
